#!/bin/bash
failures=0

ignorepep8=$(git config hooks.ignorepep8)
if [ "$ignorepep8" != "true" ]; then
	echo "Checking pep8..."
	# Run pep8 on all touched .py files
	pep8issues=0
	for file in $(exec git diff --staged --name-only | grep '\.py$'); do
		# If this repo has a pep8-blacklist.txt, obey it
		if [ -e "pep8-blacklist.txt" ]; then
			if echo "$file" | grep -Ff pep8-blacklist.txt -q; then
				continue
			fi
		fi

		if [[ -e "$file" && ! -h "$file" ]] && ! pep8 --ignore=E501,E126,E123 "$file"; then
			pep8issues=1
		fi
	done
	if [ $pep8issues == 1 ]; then
		echo "pep8 reported issues."
		failures=1
	fi
fi

ignorepep257=$(git config hooks.ignorepep257)
if [ "$ignorepep257" != "true" ]; then
	echo "Checking pep257..."
	# Run pep257 on all touched .py files
	pep257issues=0
	for file in $(exec git diff --staged --name-only | grep '\.py$'); do
		# If this repo has a pep257-blacklist.txt, obey it
		if [ -e "pep257-blacklist.txt" ]; then
			if echo "$file" | grep -Ff pep257-blacklist.txt -q; then
				continue
			fi
		fi

		if [[ -e "$file" && ! -h "$file" ]] && ! pep257 "$file"; then
			pep257issues=1
		fi
	done
	if [ $pep257issues == 1 ]; then
		echo "pep257 reported issues."
		failures=1
	fi
fi

ignorepyflakes=$(git config hooks.ignorepyflakes)
if [ "$ignorepyflakes" != "true" ]; then
	echo "Checking pyflakes..."
	# Run pyflakes on all touched .py files
	pyflakesissues=0
	for file in $(exec git diff --staged --name-only | grep '\.py$'); do
		# If this repo has a pyflakes-blacklist.txt, obey it
		if [ -e "pyflakes-blacklist.txt" ]; then
			if echo "$file" | grep -Ff pyflakes-blacklist.txt -q; then
				continue
			fi
		fi

		if [[ -e "$file" && ! -h "$file" ]] && ! pyflakes "$file"; then
			pyflakesissues=1
		fi
	done
	if [ $pyflakesissues == 1 ]; then
		echo "Pyflakes reported issues."
		failures=1
	fi
fi

if [ $failures -ne 0 ]; then
	echo "(Use 'git commit --no-verify' to bypass.)"
	exit 1
fi
