package:
  name: mako
  version: !!str 1.0.0

source:
  fn: Mako-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/M/Mako/Mako-1.0.0.tar.gz
  md5: ae27c6512832fe528bb67f1a851921cc
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mako = mako:main
    #
    # Would create an entry point called mako that calls mako.main()

    - mako-render=mako.cmd:cmdline

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - markupsafe >=0.9.2

  run:
    - python
    - setuptools
    - markupsafe >=0.9.2

test:
  # Python imports
  imports:
    - mako
    - mako.ext

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - mako-render --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.makotemplates.org/
  license: MIT
  summary: 'A super-fast templating language that borrows the  best ideas from the existing templating languages.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
