package:
  name: sphinx_rtd_theme
  version: !!str 0.1.6

source:
  fn: sphinx_rtd_theme-0.1.6.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinx_rtd_theme/sphinx_rtd_theme-0.1.6.tar.gz
  md5: 8df56a300c8c69f17e1ffbee194b2a26
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinx_rtd_theme = sphinx_rtd_theme:main
    #
    # Would create an entry point called sphinx_rtd_theme that calls sphinx_rtd_theme.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.1

  run:
    - python
    - sphinx >=1.1

test:
  # Python imports
  imports:
    - sphinx_rtd_theme

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/snide/sphinx_rtd_theme/
  license: BSD License
  summary: 'ReadTheDocs.org theme for Sphinx, 2013 version.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
