package:
  name: pyramid_mako
  version: !!str 1.0.2

source:
  fn: pyramid_mako-1.0.2.tar.gz
  url: https://pypi.python.org/packages/source/p/pyramid_mako/pyramid_mako-1.0.2.tar.gz
  md5: ee25343a97eb76bd90abdc2a774eb48a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyramid_mako = pyramid_mako:main
    #
    # Would create an entry point called pyramid_mako that calls pyramid_mako.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyramid
    - mako >=0.8

  run:
    - python
    - pyramid
    - mako >=0.8

test:
  # Python imports
  imports:
    - pyramid_mako

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Pylons/pyramid_mako
  license: BSD-derived (http://www.repoze.org/LICENSE.txt)
  summary: 'Mako template bindings for the Pyramid web framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
