package:
  name: simplejson
  version: !!str 3.6.5

source:
  fn: simplejson-3.6.5.tar.gz
  url: https://pypi.python.org/packages/source/s/simplejson/simplejson-3.6.5.tar.gz
  md5: b65dc21c7aaad14c6b4ad0d9179e437d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - simplejson = simplejson:main
    #
    # Would create an entry point called simplejson that calls simplejson.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - simplejson
    - simplejson.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/simplejson/simplejson
  license: MIT License or Academic Free License (AFL)
  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
