package:
  name: zope.deprecation
  version: !!str 4.1.1

source:
  fn: zope.deprecation-4.1.1.tar.gz
  url: https://pypi.python.org/packages/source/z/zope.deprecation/zope.deprecation-4.1.1.tar.gz
  md5: ce261b9384066f7e13b63525778430cb
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zope.deprecation = zope.deprecation:main
    #
    # Would create an entry point called zope.deprecation that calls zope.deprecation.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - zope
    - zope.deprecation

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/zope.deprecation
  license: ZPL 2.1
  summary: 'Zope Deprecation Infrastructure'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
