package:
  name: paste
  version: !!str 1.7.5.1

source:
  fn: Paste-1.7.5.1.tar.gz
  url: https://pypi.python.org/packages/source/P/Paste/Paste-1.7.5.1.tar.gz
  md5: 7ea5fabed7dca48eb46dc613c4b6c4ed
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - paste = paste:main
    #
    # Would create an entry point called paste that calls paste.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - paste
    - paste.auth
    - paste.cowbell
    - paste.debug
    - paste.evalexception
    - paste.exceptions
    - paste.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonpaste.org
  license: MIT License
  summary: 'Tools for using a Web Server Gateway Interface stack'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
