package:
  name: backports.ssl_match_hostname
  version: !!str 3.4.0.2

source:
  fn: backports.ssl_match_hostname-3.4.0.2.tar.gz
  url: https://pypi.python.org/packages/source/b/backports.ssl_match_hostname/backports.ssl_match_hostname-3.4.0.2.tar.gz
  md5: 788214f20214c64631f0859dc79f23c6
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - backports.ssl_match_hostname = backports.ssl_match_hostname:main
    #
    # Would create an entry point called backports.ssl_match_hostname that calls backports.ssl_match_hostname.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - backports
    - backports.ssl_match_hostname

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/brandon/backports.ssl_match_hostname
  license: Python Software Foundation License
  summary: 'The ssl.match_hostname() function from Python 3.4'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
