package:
  name: sphinxcontrib-httpdomain
  version: !!str 1.3.0

source:
  fn: sphinxcontrib-httpdomain-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/s/sphinxcontrib-httpdomain/sphinxcontrib-httpdomain-1.3.0.tar.gz
  md5: ad7ea42bd4c7c0ee57b1cb25bbf24aab
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - sphinxcontrib-httpdomain = sphinxcontrib-httpdomain:main
    #
    # Would create an entry point called sphinxcontrib-httpdomain that calls sphinxcontrib-httpdomain.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - sphinx >=1.0
    - six

  run:
    - python
    - sphinx >=1.0
    - six

test:
  # Python imports
  imports:
    - sphinxcontrib
    - sphinxcontrib.autohttp

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/birkenfeld/sphinx-contrib
  license: BSD License
  summary: 'Sphinx domain for HTTP APIs'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
